# Generated by Django 4.1.5 on 2023-03-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Cake", "Cake"),
                    ("Cookie", "Cookie"),
                    ("Pie", "Pie"),
                    ("Cupcake", "Cupcake"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
